#!/bin/bash

res=$(rofi -dmenu -bg "#1a1a1a" -fg "#867d59" < ~/.dmenu-i3exit)

if [ $res = "logout" ]; then
	i3-msg exit
fi
if [ $res = "restart" ]; then
	reboot
fi
if [ $res = "shutdown" ]; then
	poweroff
fi
exit 0
