#!/bin/bash

res=$(rofi -p "> " -dmenu < ~/.i3/powermenu)

if [ $res = "lock" ]; then
	~/.i3/lock/lock
fi
if [ $res = "logout" ]; then
	i3-msg exit
fi
if [ $res = "restart" ]; then
	reboot
fi
if [ $res = "shutdown" ]; then
	poweroff
fi
exit 0
